# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13396f57093f10c757e6ba729894a1580be2f404e537f0a092e41c1865f5358e8f3f1cdd4c0c00e4ad966c981955acfd2ee4574ab96129f7bc29177318bf1d19

test:
  secret_key_base: 3234a9c502ef7e6769fe7d0949ad5def8e7da2a1a792cbd2abfc5af031d5df038bda67c912b5697de11c4653c3ef6737aed48db4e1d4c5ee44f9f08be27db081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
